### ISSUE TITLE
PPS above 11V exits after 5 seconds of triggering

### ISSUE THREAD

**Issue by sakura-ushio** [ryan-ma/PD_Micro#4]
My charger supports 5-20V 5A PPS, but it will exit PPS 5 seconds after triggering PPS above 11v. Why？

**Comment by ryan-ma** [comment]
Hi, I just realize a bug that may related to your problem.
The power_data_obj[] array in PD_protocol_t should be size of 7 instead of 6, which will cause power negotiation fail or even crash if number of PDO is more than 6. 
I pushed the fix. See if this can solve your issue.

**Comment by sakura-ushio** [comment]
Now the PPS above 11V works perfectly.
